Resources:
  DBMasterSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: "${self:service}-${self:provider.stage}-DB-master-secret"
      Description: "RDS Master credentials for ${self:service}-${self:provider.stage}"
      SecretString: '{"username": "possu", "host": "localhost.localstack.cloud", "port": "4510", "dbname": "test", "password": "test"}'
  DBAppSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: "${self:service}-${self:provider.stage}-DB-app-secret"
      Description: "RDS App credentials for ${self:service}-${self:provider.stage}"
      SecretString: '{"username": "exampledb", "host": "localhost.localstack.cloud", "port": "4510", "dbname": "exampledb", "password": "exampledb"}'
  APIKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ${self:service}-${self:provider.stage}-API-key-secret
      Description: 'AppSync API KEY for ${self:service}-${self:provider.stage}'
      SecretString: ${appsync:apiKey.test}
  OpenWeatherAPIKeySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ${self:service}-${self:provider.stage}-OpenWeather-API-key-secret
      Description: 'OpenWeather API key for ${self:service}-${self:provider.stage}'
    SecretString: ${env:OPENWEATHER_API_KEY}